Add OL Token Mainnet
ethereum-optimism/ethereum-optimism.github.io pull request #1005
Opened 2024-11-27 00:00 UTC by mferranti

Add OL Token in Mainnet

Mainnet:
https://etherscan.io/address/0x1F57da732A77636D913C9a75d685B26CC85DCC3A

Base Mainnet:
https://basescan.org/address/0xEEB221A559F4aD1746F41460807E56d06D198A58

2024-11-29 06:23 UTC, wbnns requested changes
@mferranti 

Hi there! Thanks for this PR! CI/CD is currently failing with the following issue:
```
error: OL on chain base token 0xEEB221A559F4aD1746F41460807E56d06D198A58 could not fetch l2Bridge or l1Token.
                    This token most likely needs nobridge or a bridge override set.
warning: OL on chain base-sepolia token 0x189e5d3e8b540a9f9a5a15BAd683d26fF87E3DdE has an overridden bridge
```
Could you please update? Once you've done so we'll rereview.

If you have further assistance or have questions, just let us know. 👍

2024-11-29 20:02 UTC, mferranti commented
> @mferranti
> 
> Hi there! Thanks for this PR! CI/CD is currently failing with the following issue:
> 
> ```
> error: OL on chain base token 0xEEB221A559F4aD1746F41460807E56d06D198A58 could not fetch l2Bridge or l1Token.
>                     This token most likely needs nobridge or a bridge override set.
> warning: OL on chain base-sepolia token 0x189e5d3e8b540a9f9a5a15BAd683d26fF87E3DdE has an overridden bridge
> ```
> 
> Could you please update? Once you've done so we'll rereview.
> 
> If you have further assistance or have questions, just let us know. 👍

Thanks. I've added a bridge override.

2024-12-05 03:39 UTC, NaNOteh approved these changes

2024-12-10 01:44 UTC, wbnns approved these changes
ACK

@mferranti Thanks for building on Base 🔵

2024-12-10 01:45 UTC, merged