Add QWLA Token
ethereum-optimism/ethereum-optimism.github.io pull request #1035
Opened 2024-12-30 04:49 UTC by bevanz

**Description** Request - Adding QWLA Token to the Base chain bridge list

**Tests**

**Additional context**

**Metadata**

2024-12-30 09:39 UTC, wbnns requested changes
@bevanz 

Hi there! Thanks for this PR! CI/CD is currently failing because the logo file name does not match the specification mentioned in the README. Please fix and we will re-review. 👍

2024-12-31 20:15 UTC, bevanz reviewed
updating image name from notes provided on last CR attempt. Thanks!

2025-01-01 19:39 UTC, bevanz commented
updated file type... PNG -> SVG sorry for that confusion. Thanks!

2025-01-07 01:47 UTC, wbnns commented
@bevanz 

Thanks for the updates! Unfortunately still seeing an error:
```
error: QWLA on chain base token 0x9bb160c50db4ae4f16ce950fc1b0a100578ba14b could not fetch l2Bridge or l1Token.
This token most likely needs nobridge or a bridge override set
```
Please let me know if you have any questions. 👍

2025-01-25 04:13 UTC, bevanz commented
Hey @wbnns we have run into a blocker... 

Do we need to register the layer1 / layer 2 contracts via the Base Bridge contract? 

Currently QWLA is layer 1 and we have deployed layer 2 on Base. Thanks for any help or suggestions! 

EX:

_localToken: 0x1D96Fd43EE07Aa79f8Fd003cbdF404fb5ce41AD2 (L1 QWLA token address).
_remoteToken: 0x9bb160c50db4ae4f16ce950fc1b0a100578ba14b (L2 QWLA token address on Base).
_amount: 0 (Set to zero for registration purposes).
_minGasLimit: 200000.
_extraData: Leave blank or input 0x.

2025-01-25 11:23 UTC, wbnns commented
@bevanz 

Hello, I would recommend doing a test deployment on Sepolia and Base Sepolia, and specifying the Base bridge contract addresses in the metadata, then testing to ensure you can deposit and withdrawal as intended before putting into production on mainnet

2025-01-29 04:00 UTC, bevanz commented
Hi There, Thanks for the suggestion.. We did go to the Sepolina networks (ETH and Base) and see the same issues on main ETH network when we bridge. I did attempt to open a ticket with base dev support but have not heard back yet. Here is the message I sent to them. Please let us know if you have any suggestions. :) 

Summary we built the layer 2 contract on base, set bridge contract address on layer 2 contract. Made sure Base Bridge contract on ETH has spender privilege on QWLA contract and also tried to create a wrapper contract the bridge, still no luck... 

Here is the main contract ( old not amazing but simple ) - https://etherscan.io/token/0x1d96fd43ee07aa79f8fd003cbdf404fb5ce41ad2

Our bridge contract on base - https://basescan.org/token/0x9bb160c50db4ae4f16ce950fc1b0a100578ba14b

When we attempt to bridge we get success but reverted... Here is a sample trx hash - https://etherscan.io/tx/0x78dd8491c79291d8aa3901c32a7766e3b2d437f2d017749232aa63f6a9681583

Once these issues seemed to be deeper we moved back over to the Base test net, still seeing same issues... 

QWLA ( Sepolia ) - https://sepolia.etherscan.io/token/0xa202f3ede50ec5c904e69edcd7b5b41b4d656a01
QWLA Bridge ( Sepolia.Base ) - https://sepolia.basescan.org/address/0xa202f3ede50ec5c904e69edcd7b5b41b4d656a01
Sample TRX hash from bridge attempt ) - https://sepolia.etherscan.io/tx/0x701a5a3f0515429343405e0542f91ad88ad02517943d56853e7cdd88ff4c051d

Please let us know if you have any suggestions or questiosn. thanks!

2025-01-29 04:01 UTC, bevanz commented
![image](https://github.com/user-attachments/assets/8dede620-05a2-4aa2-bcba-eff936654407)

This is an image of the failures in staticcall_0_1_1

2025-01-31 04:29 UTC, closed without merging