Add POOL token on Optimism to token list
ethereum-optimism/ethereum-optimism.github.io pull request #116
Opened 2022-07-28 22:27 UTC by chuckbergeron

Add POOL token on Optimism to token list

2022-07-31 12:54 UTC, roninjin10 commented on optimism.tokenlist.json
> +    },
syntax error is failing the tests.  Please remove this comma

2022-07-31 12:54 UTC, roninjin10 requested changes
Syntax error failing tests

2022-08-01 13:05 UTC, Nicca42 commented
We also only need one image, recommend leaving the SVG and deleting the PNG.

2022-08-01 17:07 UTC, chuckbergeron commented
@Nicca42 @roninjin10 great, thanks. Those have been fixed!

2022-08-01 22:14 UTC, roninjin10 approved these changes

2022-08-03 17:15 UTC, chuckbergeron commented
@roninjin10 I believe this is good to go now. We noticed there was an issue with the `validate` task due to the Optimism bridge address I used being lowercase instead of checksummed. I don't see it running again on GitHub actions, but it's running fine for me locally. Thanks again.

2022-08-04 14:18 UTC, roninjin10 commented
@chuckbergeron the lowercase thing has been fixed.   Check is failing for odd reason.  Can you merge your changes with latest master and try again?

2022-08-04 23:17 UTC, chuckbergeron commented
@roninjin10 Ok done. Could we give the GitHub action another go? This branch is acting wonky for me. If it doesn't work this time I'll close this PR and create a new branch & PR. 👍

2022-08-05 01:54 UTC, roninjin10 commented
tyty @chuckbergeron

2022-08-05 01:54 UTC, merged