Add CTSI
ethereum-optimism/ethereum-optimism.github.io pull request #181
Opened 2022-09-05 15:00 UTC by colinsteil

**Description**
Add CTSI to the Optimism Bridge.

2022-09-15 05:12 UTC, colinsteil commented
Hey. Is there anything required on my end in order for this to pass? Much appreciated!

2022-09-20 09:11 UTC, colinsteil commented
Hey, sorry, is there anything I need to do in order for it to validate? Much appreciated!

2022-09-24 03:33 UTC, smartcontracts commented
Hey @colinsteil sorry about the delayed response here, we had some issues with the way we were leaving automated comments. I'm trying to get the bot running again. In the meantime, here's the error that was generated:

```
undefined:2
  "name": “Cartesi Token”,
          ^

SyntaxError: Unexpected token “ in JSON at position 12
    at JSON.parse (<anonymous>)
    at /home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/src/generate.js:27:25
    at Array.map (<anonymous>)
    at generate (/home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/src/generate.js:26:6)
    at validate (/home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/src/validate.js:247:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/bin/cli.js:21:21)
```

This is probably because you're using “ instead of " (smart quotes instead of normal quotes).

2022-09-24 07:39 UTC, colinsteil commented
Hey @smartcontracts got it, thanks a bunch! I've just updated these - let me know if all good. Cheers

2022-09-24 18:52 UTC, smartcontracts commented on data/CTSI/data.json
> +  "description": "Cartesi - The Blockchain OS is a decentralized Layer-2 infrastructure that supports Linux and mainstream software components. For the first time, developers can code scalable smart
Last thing here -- make sure not to use newlines in the description, instead use `\n` where you want newlines to appear. But probably better to just not use newlines at all.

2022-09-29 23:56 UTC, colinsteil commented
Hey @smartcontracts all good? Thanks for the help!

2022-10-07 21:14 UTC, roninjin10 requested changes

2022-10-07 21:14 UTC, roninjin10 commented on data/CTSI/data.json
> +    },
one last issue this comma needs to be removed for this to be valid jsonone last issue this comma needs to be removed for this to be valid json

2022-10-07 23:30 UTC, merged