Add SUS to Base
ethereum-optimism/ethereum-optimism.github.io pull request #471
Opened 2023-08-16 20:16 UTC by PlaguePatientZero

Sustainable growth is a token focussed on an incetivized token locking mechanism to stimulate slow and steady ecosystem growth. Token is deployed on Base chain.

2023-08-16 20:19 UTC, PlaguePatientZero commented
@roberto-bayardo

2023-08-17 13:55 UTC, roberto-bayardo requested changes

2023-08-17 13:55 UTC, roberto-bayardo commented on data/SUS/data.json
> +  "tokens": {
Please add the "nobridge": true tag since this is a native L2 token.

2023-08-18 18:58 UTC, hamdiallam commented
cc @roberto-bayardo for another pass

2023-08-19 01:11 UTC, ericm-cb commented
Hey @hamdiallam, can you guys explain 2 things:
1. What is the purpose of the LockedFunds in the transfer function? Will this at all impact the ability for a recipient to transfer/receive the full amount intended?

2. Why is the amount being set to 0 after the expired lock in the _beforeTokenTransfer function? Will this also impact the ability for a recipient to transfer/receive the full amount intended?

Thank you!

2023-08-19 08:26 UTC, PlaguePatientZero commented
> Hey @hamdiallam, can you guys answer the following question:
> 
> 1. What is the purpose of the LockedFunds in the transfer function? Will this at all impact the ability for a recipient to transfer/receive the full amount intended?
> 
> Thank you!

Hi good question I made the code, you can look up the corresponding contracts of the token. The locked time is depending on the amount bought and equal to blockstowait = 150* sqrt(amount). In addition each wallet mints 20% tokens for free. Swapping works fine both ways it is just to inventive people locking longer for more value.

2023-08-21 15:32 UTC, roberto-bayardo approved these changes
approved for base

2023-08-22 22:24 UTC, annieke approved these changes

2023-08-22 22:25 UTC, merged