Adds sUSD L2 addresses
ethereum-optimism/ethereum-optimism.github.io pull request #5
Opened 2021-07-14 17:47 UTC by gigamesh

address reference:
https://raw.githubusercontent.com/Synthetixio/synthetix/develop/publish/deployed/kovan-ovm/deployment.json
https://raw.githubusercontent.com/Synthetixio/synthetix/develop/publish/deployed/mainnet-ovm/deployment.json

2021-07-14 23:48 UTC, K-Ho requested changes
need to update chain ids, but other than that looks good

2021-07-14 23:48 UTC, K-Ho commented on optimism.tokenlist.json
> +      "chainId": 42,
```suggestion
      "chainId": 69,
```

2021-07-14 23:48 UTC, K-Ho commented on optimism.tokenlist.json
> +      "chainId": 69,
```suggestion
      "chainId": 10,
```

2021-07-16 04:57 UTC, elenadimitrova approved these changes

2021-07-16 06:40 UTC, merged