Add USDGLO
ethereum-optimism/ethereum-optimism.github.io pull request #502
Opened 2023-08-28 18:32 UTC by chasemerlin

Add USDGLO on Base @roberto-bayardo

2023-08-30 16:59 UTC, nickbalestra commented
Hi @chasemerlin See the error here https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/6003576065/job/16326970660?pr=502#step:10:64 .

Also adding @roberto-bayardo for base review

2023-09-22 21:41 UTC, roninjin10 requested changes

2023-09-22 21:41 UTC, roninjin10 commented on data/USDGLO/data.json
> +        "address": "0x4F604735c1cF31399C6E711D5962b2B3E0225AD3"
This token is not bridgable with native OP-stack bridging. Please add a nobridge field and comment how this is bridgable. E.g. layer zero token

2023-10-07 01:45 UTC, closed without merging

2023-10-16 19:18 UTC, Hmandalkar commented
Hi @chasemerlin 
Could you please provide information on how the privileged account's (Which has upgrade privilege) access is controlled? Multisig etc