Add base address of PYUSD
ethereum-optimism/ethereum-optimism.github.io pull request #523
Opened 2023-09-07 02:14 UTC by skellet0r

2023-09-07 15:51 UTC, roberto-bayardo commented
Unfortunately the current factory doesn't support custom decimal amounts.

```
error: PYUSD on chain base token 0x5fd0787a5A66D24C5a868c2e6a296ca2B1452558 has incorrect decimals
```

if you can hang tight for a bit, @hamdiallam should be sharing a new factory implementation soon that does allow custom decimals, which you can use to de-deploy the L2 token.

2023-09-07 19:38 UTC, hamdiallam commented
+1 will share a temp solution soon

2023-09-12 22:45 UTC, hamdiallam commented
Hey @skellet0r, the factory and OptimismMintableERC20 contracts in the develop branch of ethereum-optimism/optimism was just updated such that decimals can be sepecified. Here's the associated PR https://github.com/ethereum-optimism/optimism/pull/7182.

I would recommend getting a deployment of the factory up yourself to use to generate the right L2 token. Eventually we'll have our factories updated

2023-09-22 21:39 UTC, roninjin10 requested changes

2023-09-22 21:39 UTC, roninjin10 commented on data/PYUSD/data.json
> +  "decimals": 6,
hey @skellet0r let me know if you need any help updating this with the new factory

2023-10-07 01:45 UTC, closed without merging