add AELIN to token list
ethereum-optimism/ethereum-optimism.github.io pull request #63
Opened 2022-01-12 21:50 UTC by alextheboredape

**Description**
A clear and concise description of the features you're adding in this pull request.
Adding the AELIN token for the Aelin Protocol

**Additional context**
Add any other context about the problem you're solving.

**Metadata**
- Fixes #[Link to Issue]

2022-01-13 10:02 UTC, elenadimitrova requested changes

2022-01-13 10:21 UTC, elenadimitrova commented
Also please use a square image of roughly 256x256 pt size, for example the one you use on Coingecko should work.

2022-01-13 16:48 UTC, 0xcdb commented on optimism.tokenlist.json
> +    },
@elenadimitrova Aelin doesn't have a L1 address. Is it mandatory to have one?

2022-01-14 10:29 UTC, elenadimitrova commented on optimism.tokenlist.json
> +    },
If AELIN is L2 native then you don't want to bridge it and should remove the `extensions` section and its `optimismBridgeAddress` entry. See how [sLINK](https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/optimism.tokenlist.json#L396) is setup for example.

2022-01-14 15:51 UTC, 0xcdb commented on optimism.tokenlist.json
> +    },
Right, makes sense. Thanks @elenadimitrova

2022-01-17 09:06 UTC, elenadimitrova commented on optimism.tokenlist.json
> +    },
Can you please remove the `"extensions": {` section so we can merge

2022-02-16 07:44 UTC, K-Ho commented on optimism.tokenlist.json
> +    },
Hey @0xcdb bump on removing the `"extensions": {` section so we can merge :)

2022-04-20 15:03 UTC, mctopcat commented
Test

2022-05-02 20:01 UTC, alextheboredape commented on optimism.tokenlist.json
> +    },
Apologies for the delay. We need to improve our github notifications settings. I have removed the extensions part @elenadimitrova @K-Ho

2022-05-12 09:59 UTC, Nicca42 requested changes
Please rebase with master so CI passes, then we can get you merged in 😌 
@0xcdb

2022-06-02 21:34 UTC, alextheboredape commented
@Nicca42 @elenadimitrova I have rebased off master and need the workflow to be approved so CI will pass and we can merge this

2022-06-23 10:17 UTC, Nicca42 approved these changes

2022-06-23 10:24 UTC, merged