Add SEAM Sepolia addresses and remove noBridge
ethereum-optimism/ethereum-optimism.github.io pull request #653
Opened 2024-02-20 00:41 UTC by fredwes

**Description**

When SEAM was originally added to the STL we were asked to add the noBridge tag since automated tests were not working for tokens that are native on L2 (i.e.: the bridged token is on L1 and the source of truth is on L2). But this has caused some downstream issues for UIs that automatically parse the STL, these UIs are mistakenly ignoring SEAM. In this PR I have removed noBridge and explicitly defined the bridge contract addresses to use for SEAM on each chain.

Original PR: #594 

Also, adding deployment addresses for SEAM on Sepolia for testing, since Goerli is being deprecated.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-02-20 16:53 UTC, roninjin10 commented
This pr is failing validation

```
[ 'SEAM' ]
 ELIFECYCLE  Command failed with exit code 1.
error: SEAM: instance.tokens.goerli: is not allowed to have the additional property "bridge"
error: SEAM: instance.tokens.sepolia: is not allowed to have the additional property "bridge"

2024-03-07 06:38 UTC, roninjin10 requested changes

2024-03-07 06:38 UTC, roninjin10 commented on data/SEAM/data.json
> +        }
Goerli is being discontinued remove this and it will fix another validation error

2024-03-20 21:18 UTC, hamdiallam approved these changes

2024-03-20 21:18 UTC, merged