Add ZORA network details
ethereum-optimism/ethereum-optimism.github.io pull request #658
Opened 2024-02-26 22:08 UTC by iainnash

**Description**

The ZORA network information is not included in these token lists.

**Tests**

The updated data is static and the generate scripts run correctly.

**Additional context**

The only net new other than well-known chain configuration for ZORA is a new deployment of FiatOVMToken to Sepolia.

2024-02-26 22:08 UTC, iainnash commented on bin/cli.ts
> +          `re-run the validation locally run: ` +
this was added from `pnpm run lint`

2024-02-26 22:09 UTC, iainnash commented on optimism.tokenlist.json
> +        "baseBridgeAddress": "0x735aDBbE72226BD52e818E7181953f42E3b0FF21",
this must have been changed in the data folder.

2024-02-26 22:09 UTC, iainnash commented on src/chains.ts
> +      'https://mainnet.mode.network'
updated from lint

2024-02-27 07:23 UTC, philliprossii commented
Zora Network Mainnet

NAME	VALUE
Network	Zora
Chain ID	7777777
Gas Token	ETH
RPC	https://rpc.zora.energy
Websocket	wss://rpc.zora.energy
Block Explorer	https://explorer.zora.energy

2024-03-07 06:36 UTC, roninjin10 requested changes

2024-03-07 06:36 UTC, roninjin10 commented on src/types.ts
> +] as const
There is a merge conflict here

2024-03-08 03:32 UTC, iainnash commented on src/types.ts
> +] as const
@roninjin10 Fixed the merge conflict.

2024-03-08 16:58 UTC, iainnash commented on src/chains.ts
> +  zora: {
Fixed, will take a look.

2024-03-08 21:30 UTC, roninjin10 commented
Zora needs to be added to validators

```
[ 'BridgedUSDC', 'ETH', 'WETH' ]
 ELIFECYCLE  Command failed with exit code 1.
error: BridgedUSDC: instance.tokens: is not allowed to have the additional property "zora"
error: BridgedUSDC: instance.tokens: is not allowed to have the additional property "zora-sepolia"
error: ETH: instance.tokens: is not allowed to have the additional property "zora-sepolia"
error: ETH: instance.tokens: is not allowed to have the additional property "zora"
error: WETH: instance.tokens: is not allowed to have the additional property "zora"
error: WETH: instance.tokens: is not allowed to have the additional property "zora-sepolia"
error: final token list is invalid
```

2024-03-08 21:58 UTC, iainnash commented
@roninjin10 I've updated the validate script RPCs to work in this PR as well.

Output:

```
warning: BridgedUSDC on chain base token 0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA has overridden symbol
warning: BridgedUSDC on chain base token 0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA has overridden name
warning: BridgedUSDC on chain base-goerli token 0x853154e2A5604E5C74a2546E2871Ad44932eB92C has overridden symbol
warning: BridgedUSDC on chain base-goerli token 0x853154e2A5604E5C74a2546E2871Ad44932eB92C has overridden name
warning: BridgedUSDC on chain optimism token 0x7F5c764cBc14f9669B88837ca1490cCa17c31607 has overridden symbol
warning: BridgedUSDC on chain optimism token 0x7F5c764cBc14f9669B88837ca1490cCa17c31607 has overridden name
warning: BridgedUSDC on chain optimism-goerli token 0x7E07E15D2a87A24492740D16f5bdF58c16db0c4E has overridden symbol
warning: BridgedUSDC on chain optimism-goerli token 0x7E07E15D2a87A24492740D16f5bdF58c16db0c4E has overridden name
warning: BridgedUSDC on chain zora token 0xCccCCccc7021b32EBb4e8C08314bD62F7c653EC4 has overridden symbol
warning: BridgedUSDC on chain zora token 0xCccCCccc7021b32EBb4e8C08314bD62F7c653EC4 has overridden name
warning: BridgedUSDC on chain zora-sepolia token 0xccCcCc4532d20C06726866e328F7478Edabf907B has overridden symbol
warning: BridgedUSDC on chain zora-sepolia token 0xccCcCc4532d20C06726866e328F7478Edabf907B has overridden name
warning: ETH on chain ethereum token 0x0000000000000000000000000000000000000000 is a nonstandard token
warning: ETH on chain optimism token 0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000 is a nonstandard token
warning: ETH on chain goerli token 0x0000000000000000000000000000000000000000 is a nonstandard token
warning: ETH on chain sepolia token 0x0000000000000000000000000000000000000000 is a nonstandard token
warning: ETH on chain optimism-goerli token 0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000 is a nonstandard token
warning: ETH on chain optimism-sepolia token 0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000 is a nonstandard token
warning: ETH on chain zora-sepolia token 0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000 is a nonstandard token
warning: ETH on chain zora token 0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000 is a nonstandard token


```

2024-03-11 15:47 UTC, iainnash commented
@roninjin10 The PR has been updated and fixed all merge conflicts. The verify script also now runs.

2024-03-11 16:15 UTC, roninjin10 commented
Still seeing a validation error though it's not obvious why at first glance

2024-03-11 16:18 UTC, iainnash commented
@roninjin10 I believe this script is broken in main. I've corrected all errors associated with our tokenlist locally, however, I can attempt to fix this error.

2024-03-12 21:36 UTC, hamdiallam commented on optimism.tokenlist.json
> +        "baseBridgeAddress": "0x3e2Ea9B92B7E48A52296fD261dc26fd995284631",
we'll need to fix this. I believe this is Zora's bridge address?

2024-03-12 21:39 UTC, iainnash commented
I can add in a zoraBridgeAddress field?

On Tue, Mar 12, 2024 at 5:37 PM Hamdi Allam ***@***.***>
wrote:

> Taking a look at our validation scripts
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/658#issuecomment-1992629240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGMCOCH57PYCBIQRI7EWSLYX5YSFAVCNFSM6AAAAABD274KKSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJSGYZDSMRUGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2024-03-12 22:58 UTC, hamdiallam commented
@iainnash I see, it looks like we hardcode the bridge address. I think when generating the token list we should dynamically construct this key using the chain name rather than hardcoding it. We have the chain string and create the name appropriately from it

feel free to add `zoraBridgeAddress` for now here and I can followup with a better fix for this longer term

2024-03-12 23:49 UTC, iainnash commented
Great, I can do that.


Iain

On Tue, Mar 12, 2024 at 6:58 PM Hamdi Allam ***@***.***>
wrote:

> @iainnash <https://github.com/iainnash> I see, it looks like we hardcode
> the bridge address. I think when generating the token list we should
> dynamically construct this key using the chain name rather than hardcoding
> it. We have the chain string and create the name appropriately from it
>
> feel free to add zoraBridgeAddress for now here and I can followup with a
> better fix for this longer term
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/658#issuecomment-1992711014>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGMCOCR2BJRO7VTABNBCF3YX6CA7AVCNFSM6AAAAABD274KKSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJSG4YTCMBRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2024-03-13 06:54 UTC, hamdiallam commented
published #689 . Maybe you can try rebasing this PR on top that and regenerating the tokenlist

2024-05-16 16:45 UTC, hamdiallam commented
Hey @iainnash , feel free to reopen after rebasing!

2024-05-16 16:45 UTC, closed without merging