feat: add ZOOMER
ethereum-optimism/ethereum-optimism.github.io pull request #688
Opened 2024-03-11 12:54 UTC by rhlsthrm

**Description**

Add Optimism and Base configs for Zoomer.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-03-11 17:24 UTC, rhlsthrm commented
These are not tokens that are minted from the OP bridge by the way, that's why the validation is failing I believe.

2024-03-11 17:25 UTC, rhlsthrm commented
cc @roberto-bayardo

2024-03-12 01:04 UTC, roninjin10 commented
Might need to add a nobridge: true property if they aren't Optimism standard tokens

2024-03-12 09:40 UTC, rhlsthrm commented
Thanks @roninjin10 I missed this in the readme. Just modified to add the property.

2024-03-20 20:59 UTC, hamdiallam commented
Hi! The validation script needs to pass. It looks like the logo must be of filename `logo.png`. Otherwise looks good on OP side and needs a base approval

2024-03-26 16:05 UTC, cfluke-cb commented
"name": "ZoomerCoin", should be "name": "ZOOMER"

2024-04-02 14:35 UTC, cfluke-cb commented
Hi @rhlsthrm This is still not passing validation. I am currently getting errors
error: ZOOMER on chain optimism token 0xB962150760F9A3bB00e3E9Cf48297EE20AdA4A33 has incorrect symbol
error: ZOOMER on chain optimism token 0xB962150760F9A3bB00e3E9Cf48297EE20AdA4A33 has incorrect name. Got xZoomerCoin
error: ZOOMER on chain base token 0xD1dB4851bcF5B41442cAA32025Ce0Afe6B8EabC2 has incorrect name. Got Based ZoomerCoin 

Locally you can run 
npx tsx ./bin/cli.ts validate --datadir ./data --tokens ZOOMER
to test this yourself

2024-04-08 13:08 UTC, rhlsthrm commented
OK I see the problem here, it's that the token has different names and symbols on different chains. Should I break them into separate folders?

2024-04-08 13:10 UTC, rhlsthrm commented
Btw, I can't run the validate script locally, I get this error:

```
npx tsx ./bin/cli.ts validate --datadir ./data --tokens ZOOMER
(node:90737) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///Users/rahul/dev/projects/zoomer/ethereum-optimism.github.io/node_modules/.pnpm/tsx%403.12.6/node_modules/tsx/dist/loader.js", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
[ 'ZOOMER' ]
node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOTDIR: not a directory, open 'data/.DS_Store/data.json'
    at Object.readFileSync (node:fs:453:20)
    at <anonymous> (/Users/rahul/dev/projects/zoomer/ethereum-optimism.github.io/src/generate.ts:35:12)
    at Array.map (<anonymous>)
    at generate (/Users/rahul/dev/projects/zoomer/ethereum-optimism.github.io/src/generate.ts:33:6)
    at validate (/Users/rahul/dev/projects/zoomer/ethereum-optimism.github.io/src/validate.ts:328:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Command.<anonymous> (/Users/rahul/dev/projects/zoomer/ethereum-optimism.github.io/bin/cli.ts:25:21) {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'open',
  path: 'data/.DS_Store/data.json'
}

Node.js v20.11.1
```

2024-04-08 13:25 UTC, rhlsthrm commented
I tried breaking it up based on the output you pasted, apologies for I can't run the test scripts locally for some reason.

2024-04-09 05:43 UTC, rhlsthrm commented
In my latest commit I removed Ethereum from the chains because the Ethereum and Base tokens are named differently. How can I handle this case properly?

2024-04-15 16:24 UTC, cfluke-cb commented
Hi @rhlsthrm You can override the names and symbols like this: https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/e1c95f902eb0d5a12df2e5db0bfebf450835017c/README.md?plain=1#L174

2024-04-26 14:56 UTC, wbnns requested changes
@rhlsthrm 

Thanks for the updates; requested an additional change.

2024-04-26 14:56 UTC, wbnns commented on data/ZOOMER/data.json
> +        "symbol": "ZOOMER"
This can be dropped since the symbol is already defined on Line 3.

2024-04-30 02:49 UTC, wbnns requested changes
@rhlsthrm 

Thanks for the update. Can you also please add the `"nonstandard": true,` option to your JSON?

2024-04-30 09:47 UTC, rhlsthrm commented
@wbnns done

2024-05-01 00:32 UTC, wbnns approved these changes
ACK

2024-05-06 20:55 UTC, hamdiallam approved these changes

2024-05-06 20:55 UTC, merged