FEDUP Token on Base
ethereum-optimism/ethereum-optimism.github.io pull request #783
Opened 2024-04-11 09:59 UTC by BalooSuperRareBears

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-04-26 23:10 UTC, wbnns requested changes
@BalooSuperRareBears 

Hi there! This commit on this PR is failing CI / verification, could you please resolve?

2024-04-30 18:35 UTC, BalooSuperRareBears commented
Hello, @wbnns 

I've synced my branch with the main one, let's see if it's ok now. Thanks!

2024-05-01 00:27 UTC, wbnns requested changes
@BalooSuperRareBears 

Hello, we were unable to confirm the L1 token specified in your json. Can you please double-check?

2024-05-01 00:27 UTC, wbnns commented on data/FEDUP/data.json
> +      "address": "0x6c80aeA8C83948D502c43539E22Ce2a2956Ad004"
Hm, I don't see a token deployed at this address. Can you please confirm?

2024-05-08 00:28 UTC, wbnns commented
@BalooSuperRareBears 

Since it's been a while and we haven't heard back, closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

2024-05-08 00:28 UTC, closed without merging