Add rgUSD base
ethereum-optimism/ethereum-optimism.github.io pull request #800
Opened 2024-04-24 19:53 UTC by pmckelvy1

**Description**

Add rgUSD on Base to the superchain token list.

**Tests**

n/a

**Additional context**

n/a

**Metadata**

n/a

2024-04-30 02:24 UTC, wbnns requested changes
@pmckelvy1 

Hi there! Just wanted to confirm, is the included URL the right/canonical website for the asset and/or project affiliated with it?

2024-05-02 13:49 UTC, pmckelvy1 commented
> @pmckelvy1
> 
> Hi there! Just wanted to confirm, is the included URL the right/canonical website for the asset and/or project affiliated with it?

it is the Reserve Register, the main explorer for RTokens like rgUSD.

2024-05-03 01:46 UTC, wbnns submitted a review, later dismissed
ACK

@pmckelvy1 Thanks for building on Base 🔵

2024-05-03 16:16 UTC, annieke submitted a review, later dismissed

2024-05-03 16:20 UTC, annieke approved these changes

2024-05-03 16:22 UTC, merged