Update BOME on BASE
ethereum-optimism/ethereum-optimism.github.io pull request #841
Opened 2024-05-29 13:40 UTC by alehop-hop-hop

**Description**

Updating json and image for the BOME token on BASE

**Tests**

Followed the steps

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

2024-05-29 23:23 UTC, wbnns requested changes
@alehop-hop-hop 

Hi there! After the twitter entry, can you please add the `"nonstandard": true,` option?

2024-05-29 23:41 UTC, alehop-hop-hop commented
Hi, you have it, ty

2024-06-04 15:40 UTC, wbnns approved these changes
@alehop-hop-hop 

Thanks for the updates and for building on Base 🔵

2024-06-05 16:47 UTC, hamdiallam approved these changes

2024-06-05 16:47 UTC, merged