Add BURN to Base Chain
ethereum-optimism/ethereum-optimism.github.io pull request #872
Opened 2024-06-20 21:16 UTC by realshibadoge

Add Burn Token on Base

Burn: https://www.deflationary.com/
Ethereum: 0xa2fe5e51729be71261bcf42854012827bc44c044
Base: 0x3bd3b0eaea951cc4cb05be2234eb8bc953726e08

Old issue: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/753

2024-06-21 00:22 UTC, wbnns requested changes
@realshibadoge 

Hello, the deployed token on Base doesn't match the byte code for the [OptimismMintableERC20 Factory](https://basescan.org/address/0xF10122D428B4bc8A9d050D06a2037259b4c4B83B).

Could you please update your PR using the above factory?

2024-06-21 21:56 UTC, realshibadoge commented
> @realshibadoge
> 
> Hello, the deployed token on Base doesn't match the byte code for the [OptimismMintableERC20 Factory](https://basescan.org/address/0xF10122D428B4bc8A9d050D06a2037259b4c4B83B).
> 
> Could you please update your PR using the above factory?

Updated. Let me know if any issues thank you.

2024-06-25 00:32 UTC, wbnns approved these changes
ACK

@realshibadoge Thanks for the updates and for building on Base 🔵

2024-06-25 00:51 UTC, annieke approved these changes

2024-06-25 00:52 UTC, merged