Add FBYT Token
ethereum-optimism/ethereum-optimism.github.io pull request #873
Opened 2024-06-21 08:13 UTC by mukeshspero

Add FBYT Token

**Description**

Ethereum:
https://etherscan.io/address/0xe0b2246159a195E0B5D0DC8a5F553b046F3E0fd3

Optimism:
https://optimistic.etherscan.io/address/0x5a11547df30b8b3e2be73cd0d1e004fbbf3c283f

Optimism-Sepolia
https://sepolia-optimism.etherscan.io/token/0x5341f148ac5cc1c845c34383909ddd6aac71813f

2024-07-15 05:27 UTC, mukeshspero commented
@wbnns just checking if something needs to be done from my end on this.

2024-07-26 15:18 UTC, hamdiallam approved these changes

2024-07-26 15:27 UTC, hamdiallam requested changes
Sorry I approved too early. How is this token bridged?

For some reason the validation script was not run automatically on this PR. Can you rebase?

Also if not an OptimimsMintableERC20 can you add the `nobridge` tag to this token and specify in the description the bridging protocol?

2024-08-23 04:59 UTC, mukeshspero commented
Noted.
closing for now, will raise another one with the suggested fixes.

2024-08-23 04:59 UTC, closed without merging