Update weETH token data
ethereum-optimism/ethereum-optimism.github.io pull request #892
Opened 2024-07-08 23:39 UTC by jtfirek

Bridges keep on listing the weETH canonical, but we have switched over to an layerzero OFT deployment for all OP stack chains

2024-07-12 11:22 UTC, wbnns requested changes
@jtfirek 

Hello, thanks for your PR. It looks like CI/CD is failing due to a syntax error -- `noBridge` should be `nobridge` -- could you please fix?

We'll also review the change for how this might affect people that have already bridged.

2024-07-18 01:12 UTC, wbnns commented
@jtfirek 

Hello, can you please share more details as to how users who are currently bridged over should plan to bridge back to get into the LayerZero OFT? The `nobridge` parameter will result in this version that is being updated to no longer appear in standard bridges.

2024-07-24 19:09 UTC, wbnns commented
@jtfirek 

Since it's been some time and we haven't heard back, closing this PR for now. If you're still interested in pursuing the change, please let us know regarding the [last comment](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/892#issuecomment-2235000379) and we can reopen. 👍

2024-07-24 19:09 UTC, closed without merging

2024-08-08 13:01 UTC, AlexBHarley commented
I mentioned this to EtherFi in a DM, but I believe the correct behaviour here is for the OP token list standard to support a new `nodeposit` flag.

This won't be the last time a team wants to migrate away from the native bridge representation of their asset, and as @wbnns pointed out, `nobridge` will leave users unable to withdraw their assets.