Adds CNG token data
ethereum-optimism/ethereum-optimism.github.io pull request #902
Opened 2024-07-22 15:40 UTC by 4000D

Adds CNG Token

Ethereum: https://etherscan.io/token/0x5C1d9aA868a30795F92fAe903eDc9eFF269044bf

Optimism: https://optimistic.etherscan.io/address/0x1D015bF7d8a6fb0fc30959F3e12355530086b2A5

2024-07-24 18:36 UTC, wbnns commented
Cc: @hamdiallam

2024-07-24 20:23 UTC, hamdiallam requested changes

2024-07-24 20:23 UTC, hamdiallam commented on data/CNG/data.json
> +  "description2": "Changer is a crypto liquidity aggregator that has aggregated the majority of centralized exchanges, OTCs, and on-chain decentralized exchanges regardless of the type of chains.",
```suggestion
  "description2": "Changer is a crypto liquidity aggregator that has aggregated the majority of centralized exchanges, OTCs, and on-chain decentralized exchanges regardless of the type of chains.",
```
```suggestion
  "description": "Changer is a crypto liquidity aggregator that has aggregated the majority of centralized exchanges, OTCs, and on-chain decentralized exchanges regardless of the type of chains.",
```

2024-07-25 22:12 UTC, hamdiallam approved these changes

2024-07-25 22:15 UTC, merged

2024-08-03 18:42 UTC, shreck101 approved these changes